#!/usr/bin/env php
<?php

declare(strict_types=1);

use JustSteveKing\Micro\Contracts\KernelContract;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

/**
 * @var \Psr\Container\ContainerInterface $container
 */
$container = require __DIR__ . '/bootstrap/app.php';
$kernel = $container->get(KernelContract::class);

// Load in Routes for route:list command
(require __DIR__ . '/routes/api.php')($kernel->app());

$application = $container->get(Application::class);

$application->run();
