#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use App\Console\RouteListCommand;
use JustSteveKing\Micro\Contracts\KernelContract;
use Symfony\Component\Console\Application;

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/');
$dotenv->load();

$cli = new Application(
    name: $_ENV['APP_NAME'],
    version: '0.0.1',
);

$container = require __DIR__ . '/bootstrap/app.php';

$kernel = $container->get(
    name: KernelContract::class,
);

(require __DIR__ . '/routes/api.php')($kernel->app());

$cli->add(
    command: new RouteListCommand(
        slim: $kernel->app(),
    ),
);

/**
 * Database Migration Commands
 */
$cli->addCommands(
    commands: [
        new \App\Console\Migrations\StatusCommand(),
        new \App\Console\Migrations\MigrateCommand(),
        new \App\Console\Migrations\CreateCommand(),
        new \App\Console\Migrations\RollbackCommand(),
        new \App\Console\Migrations\DumpCommand(),
        new \App\Console\Migrations\DiffCommand(),
        new \App\Console\Migrations\TestCommand(),
        new \App\Console\Migrations\CleanupCommand(),
    ],
);

// ... register commands

$cli->run();
